#:kivy 1.0.9

<UI>:
    title: 'InputDialog'
    auto_dismiss: False

    RelativeLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size

        TextInput:
            id: input
            hint_text:'Enter compounds'
            pos_hint: {'center_x': 0.5, 'center_y': 0.725}
            size_hint: 0.95, 0.5


        Label:
            id: output
            size_hint: 0.95, 0.25
            pos_hint: {'center_x': 0.5, 'top': 0.5}
